# Generated by Django 6.0 on 2025-12-17 10:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="上次修改时间"),
                ),
                (
                    "BOOK",
                    models.CharField(
                        default="UnknowBook", max_length=20, verbose_name="单词书"
                    ),
                ),
                ("LIST", models.IntegerField(default=-1, verbose_name="list")),
                (
                    "review_dates",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="所有复习日期（仅记录艾宾浩斯复习曲线时间）",
                    ),
                ),
                (
                    "review_dates_plus",
                    models.CharField(
                        default="",
                        max_length=1000,
                        verbose_name="自愿复习日期（非艾宾浩斯复习安排）",
                    ),
                ),
                (
                    "list_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("list_rate", models.FloatField(default=-1, verbose_name="表记忆率")),
                (
                    "recent_list_rate",
                    models.FloatField(default=-1, verbose_name="近期表记忆率"),
                ),
                (
                    "review_word_counts",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="list 内单词复习次数（分号分隔）set",
                    ),
                ),
                (
                    "word_num",
                    models.IntegerField(default=-1, verbose_name="list 内的单词数目"),
                ),
                (
                    "ebbinghaus_counter",
                    models.IntegerField(default=0, verbose_name="艾宾浩斯复习次数"),
                ),
                (
                    "unlearned_num",
                    models.IntegerField(default=-1, verbose_name="仍需复习单词数"),
                ),
            ],
            options={
                "db_table": "book_list",
                "ordering": ("BOOK", "LIST", "modify_time"),
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BOOK",
                    models.CharField(
                        default="Unknow_Book",
                        max_length=20,
                        unique=True,
                        verbose_name="单词书",
                    ),
                ),
                (
                    "BOOK_zh",
                    models.CharField(
                        default="未知书本",
                        max_length=20,
                        unique=True,
                        verbose_name="单词书中文",
                    ),
                ),
                (
                    "BOOK_abbr",
                    models.CharField(
                        default="❔", max_length=20, verbose_name="单词书简写"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "begin_index",
                    models.IntegerField(default=0, verbose_name="列表开始是1还是0"),
                ),
                ("hide", models.BooleanField(default=False, verbose_name="是否隐藏")),
            ],
            options={
                "db_table": "books",
                "ordering": ("create_time",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50, verbose_name="英文单词")),
                (
                    "total_num",
                    models.IntegerField(default=0, verbose_name="复习总次数"),
                ),
                ("forget_num", models.IntegerField(default=0, verbose_name="忘记次数")),
                ("rate", models.FloatField(default=-1, verbose_name="单词遗忘率")),
                ("LIST", models.IntegerField(default=0, verbose_name="list")),
                ("UNIT", models.IntegerField(default=0, verbose_name="unit")),
                ("INDEX", models.IntegerField(default=0, verbose_name="index")),
                (
                    "BOOK",
                    models.CharField(default="", max_length=20, verbose_name="单词书"),
                ),
                (
                    "history",
                    models.CharField(
                        default="", max_length=100, verbose_name="记忆历史"
                    ),
                ),
                (
                    "flag",
                    models.IntegerField(
                        choices=[(1, "太简单"), (0, "default"), (-1, "重难词")],
                        default=0,
                        verbose_name="tag",
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "ordering": ("LIST", "UNIT", "INDEX"),
            },
        ),
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="上次修改时间"),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="英文单词"
                    ),
                ),
                (
                    "mean",
                    models.CharField(
                        default="", max_length=500, verbose_name="中文释义"
                    ),
                ),
                (
                    "note",
                    models.CharField(default="", max_length=200, verbose_name="记忆法"),
                ),
                (
                    "total_num",
                    models.IntegerField(default=0, verbose_name="复习总次数"),
                ),
                ("forget_num", models.IntegerField(default=0, verbose_name="忘记次数")),
                (
                    "last_forget_num",
                    models.IntegerField(default=0, verbose_name="上次复习错误次数"),
                ),
                (
                    "sentence",
                    models.CharField(default="", max_length=800, verbose_name="例句"),
                ),
                ("rate", models.FloatField(default=-1, verbose_name="单词遗忘率")),
                (
                    "history",
                    models.CharField(
                        default="", max_length=100, verbose_name="记忆历史"
                    ),
                ),
                (
                    "flag",
                    models.IntegerField(
                        choices=[(1, "太简单"), (0, "default"), (-1, "重难词")],
                        default=0,
                        verbose_name="tag",
                    ),
                ),
                (
                    "webster",
                    models.BooleanField(
                        default=False, verbose_name="是否被WebsterBuilder收录"
                    ),
                ),
                (
                    "mnemonic",
                    models.CharField(default="", max_length=500, verbose_name="助记法"),
                ),
                (
                    "phonetic",
                    models.CharField(default="", max_length=50, verbose_name="音标"),
                ),
                (
                    "antonym",
                    models.CharField(default="", max_length=500, verbose_name="反义词"),
                ),
                (
                    "synonym",
                    models.CharField(default="", max_length=800, verbose_name="近义词"),
                ),
                (
                    "derivative",
                    models.CharField(default="", max_length=300, verbose_name="派生词"),
                ),
            ],
            options={
                "db_table": "words",
                "ordering": ("word",),
            },
        ),
    ]
